### PR TITLE
Add moko resources

### PR DESCRIPTION
**Pull request by gabrielbmoro**
## Summary

- This PR includes the library Moko Resources to share resources between platforms.

## Issue related
- Closes https://github.com/theolm/instagram-clone/issues/11

### CODE REVIEW

**Comment by theolm** [comment]
The moko setup is not working for iOS and Desktop.
It des not compile for desktop and it is crashing on iOS:

```sh
kotlin.native.internal.FileFailedToInitializeException: There was an error during file or class initialization
    at 0   instaclone                          0x10140f91b        kfun:kotlin.Error#<init>(kotlin.String?;kotlin.Throwable?){} + 143 
    at 1   instaclone                          0x101449027        kfun:kotlin.native.internal.FileFailedToInitializeException#<init>(kotlin.String?;kotlin.Throwable?){} + 143 
    at 2   instaclone                          0x101448283        ThrowFileFailedToInitializeException + 275 
    at 3   instaclone                          0x10158d91b        CallInitGlobalPossiblyLock + 759 
    ...
```

@gabrielbmoro do you mind fixing it?

**Review by theolm — CHANGES_REQUESTED** [review]
The moko setup is not working for iOS and Desktop.
It des not compile for desktop and it is crashing on iOS:

```sh
kotlin.native.internal.FileFailedToInitializeException: There was an error during file or class initialization
    at 0   instaclone                          0x10140f91b        kfun:kotlin.Error#<init>(kotlin.String?;kotlin.Throwable?){} + 143 
    at 1   instaclone                          0x101449027        kfun:kotlin.native.internal.FileFailedToInitializeException#<init>(kotlin.String?;kotlin.Throwable?){} + 143 
    at 2   instaclone                          0x101448283        ThrowFileFailedToInitializeException + 275 
    at 3   instaclone                          0x10158d91b        CallInitGlobalPossiblyLock + 759 
    ...
```

@gabrielbmoro do you mind fixing it?

**Comment by gabrielbmoro** [comment]
> The moko setup is not working for iOS and Desktop.
> It des not compile for desktop and it is crashing on iOS:
> 
> ```sh
> kotlin.native.internal.FileFailedToInitializeException: There was an error during file or class initialization
>     at 0   instaclone                          0x10140f91b        kfun:kotlin.Error#<init>(kotlin.String?;kotlin.Throwable?){} + 143 
>     at 1   instaclone                          0x101449027        kfun:kotlin.native.internal.FileFailedToInitializeException#<init>(kotlin.String?;kotlin.Throwable?){} + 143 
>     at 2   instaclone                          0x101448283        ThrowFileFailedToInitializeException + 275 
>     at 3   instaclone                          0x10158d91b        CallInitGlobalPossiblyLock + 759 
>     ...
> ```
> 
> @gabrielbmoro do you mind fixing it?

I did not test on iOS. No, I don't mind. I will take a look for sure!

**Comment by gabrielbmoro** [comment]
@theolm , can you double check if this is working on iOS?

I tested here it worked 🙏🏼

**Pull request merged**
